### ISSUE TITLE
Minecraft 1.16.5 fabric crashing on launch with this mod

### ISSUE THREAD

**Issue by LiIyKitsune** [MerchantPug/toomanyorigins#51] opened 2022-07-08 15:48 UTC
when i remove the mod it works fine, i've tried everything and all that works so far is using an earlier version which is missing newer features i want 
im on 1.16.5 fabric, afaik all the mods are up to date however if im just blind please lmk
[crash-2022-07-08_08.44.56-client.txt](https://github.com/MerchantPug/toomanyorigins/files/9073358/crash-2022-07-08_08.44.56-client.txt)

**Comment by ChrysanthCow** [comment] 2022-07-09 10:53
This seems to be an incompatibility with Immersive Armors and Apugli (a built in dependency of the mod).

The issue is that it uses an Overwrite to completely overwrite a method that I'm trying to modify.

I'll look into fixing it when I get around to Apugli 1.16.5 again

Edit: There's an issue with the compatibility on their end, this is out of my control to fix as I can't mixin to mixins.

**Comment by ChrysanthCow** [comment] 2022-07-09 11:05
~~I wanted to bring it up as an issue but it seems the developer has stopped supporting the 1.16.5 version of the mod.~~

The issue was fixed in 1.18.2, however, the dev has not fixed it on 1.16.5's end.

**Comment by ChrysanthCow** [comment] 2022-07-09 11:33
https://github.com/Luke100000/ImmersiveArmors/pull/42

I have just made a pull request for Immersive Armors to fix this issue on their end.

Hopefully it is accepted.

**Comment by LiIyKitsune** [comment] 2022-07-10 18:00
thank you for the response! in the mean time i could just remove immersive armors as i want this mod more
i can confirm removing immersive armors fixed this mod

**Comment by ChrysanthCow** [comment] 2022-07-21 06:31
Just in case you're interested. This has been fixed in Immersive Armors. You should now be able to play with the two mods together.

I'll mark this issue as closed now.

**Closed as completed by ChrysanthCow** 2022-07-21 06:31 UTC
Labels: compatibility
