### ISSUE TITLE
Game Crashed

### ISSUE THREAD

**Issue by seanxiecn** [MerchantPug/toomanyorigins#17] opened 2021-06-24 03:51 UTC
[crash-2021-06-24_11.12.55-client.txt](https://github.com/MerchantPug/toomanyorigins/files/6706094/crash-2021-06-24_11.12.55-client.txt)
my game crashed at the initializing progress, how can i fix it?

**Comment by MerchantPug** [comment] 2021-06-24 14:27
This should be fixed in the latest version of TooManyOrigins.

The issue was caused by Apoli changing things around so Apugli couldn't load correctly.

**Closed** 2021-06-27 11:21 UTC
Labels: bug
