### ISSUE TITLE
Game crashes when killing a Zombie with Lightning Breath

### ISSUE THREAD

**Issue by EnglishNarwhal** [MerchantPug/toomanyorigins#89] opened 2024-07-06 18:42 UTC
As described above, upon killing a zombie with the Dragonborn origin lightning Draconic Breath, server crashes with the error below. 

'Time: 2024-07-05 23:00:08
Description: Ticking entity

java.lang.NullPointerException: Cannot read field "f_19853_" because "entity" is null
	at net.merchantpug.apugli.condition.factory.entity.EntityInRadiusCondition.check(EntityInRadiusCondition.java:38) ~[Apugli-2.6.6+1.19.2-forge.jar%23468!/:2.6.6+1.19.2-forge] {re:classloading}
	at net.merchantpug.apugli.condition.factory.entity.EntityInRadiusCondition.check(EntityInRadiusCondition.java:14) ~[Apugli-2.6.6+1.19.2-forge.jar%23468!/:2.6.6+1.19.2-forge] {re:classloading}
	at net.merchantpug.apugli.condition.configuration.FabricConditionConfiguration.lambda$codec$0(FabricConditionConfiguration.java:13) ~[Apugli-2.6.6+1.19.2-forge.jar%23468!/:2.6.6+1.19.2-forge] {re:classloading}
	at net.merchantpug.apugli.condition.FabricEntityCondition.check(FabricEntityCondition.java:20) ~[Apugli-2.6.6+1.19.2-forge.jar%23468!/:2.6.6+1.19.2-forge] {re:classloading}
	at net.merchantpug.apugli.condition.FabricEntityCondition.check(FabricEntityCondition.java:11) ~[Apugli-2.6.6+1.19.2-forge.jar%23468!/:2.6.6+1.19.2-forge] {re:classloading}
	at io.github.edwinmindcraft.apoli.api.power.factory.EntityCondition.check(EntityCondition.java:34) ~[apoli-forge-1.19.2-2.6.1.7.jar%23465!/:1.19.2-2.6.1.7] {re:classloading,re:mixin}
	at io.github.edwinmindcraft.apoli.api.power.configuration.ConfiguredEntityCondition.check(ConfiguredEntityCondition.java:42) ~[apoli-forge-1.19.2-2.6.1.7.jar%23465!/:1.19.2-2.6.1.7] {re:classloading}
	at io.github.edwinmindcraft.apoli.common.condition.bientity.DispatchBiEntityCondition.lambda$new$4(DispatchBiEntityCondition.java:36) ~[apoli-forge-1.19.2-2.6.1.7.jar%23465!/:1.19.2-2.6.1.7] {re:classloading}
	at io.github.edwinmindcraft.apoli.common.condition.bientity.DispatchBiEntityCondition.check(DispatchBiEntityCondition.java:41) ~[apoli-forge-1.19.2-2.6.1.7.jar%23465!/:1.19.2-2.6.1.7] {re:classloading}
	at io.github.edwinmindcraft.apoli.common.condition.bientity.DispatchBiEntityCondition.check(DispatchBiEntityCondition.java:10) ~[apoli-forge-1.19.2-2.6.1.7.jar%23465!/:1.19.2-2.6.1.7] {re:classloading}
	at io.github.edwinmindcraft.apoli.api.power.factory.BiEntityCondition.check(BiEntityCondition.java:32) ~[apoli-forge-1.19.2-2.6.1.7.jar%23465!/:1.19.2-2.6.1.7] {re:classloading}
	at io.github.edwinmindcraft.apoli.api.power.configuration.ConfiguredBiEntityCondition.check(ConfiguredBiEntityCondition.java:42) ~[apoli-forge-1.19.2-2.6.1.7.jar%23465!/:1.19.2-2.6.1.7] {re:classloading}
	at net.merchantpug.apugli.platform.ForgeConditionHelper.checkBiEntity(ForgeConditionHelper.java:47) ~[Apugli-2.6.6+1.19.2-forge.jar%23468!/:2.6.6+1.19.2-forge] {re:classloading}
	at net.merchantpug.apugli.power.factory.DamageNearbyPowerFactory.execute(DamageNearbyPowerFactory.java:30) ~[Apugli-2.6.6+1.19.2-forge.jar%23468!/:2.6.6+1.19.2-forge] {re:classloading}
	at net.merchantpug.apugli.power.factory.DamageNearbyWhenHitPowerFactory.execute(DamageNearbyWhenHitPowerFactory.java:18) ~[Apugli-2.6.6+1.19.2-forge.jar%23468!/:2.6.6+1.19.2-forge] {re:classloading}
	at net.merchantpug.apugli.ApugliForgeEventHandler.lambda$onLivingHurt$11(ApugliForgeEventHandler.java:211) ~[Apugli-2.6.6+1.19.2-forge.jar%23468!/:2.6.6+1.19.2-forge] {re:classloading}
	at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?] {re:mixin}
	at net.merchantpug.apugli.ApugliForgeEventHandler.onLivingHurt(ApugliForgeEventHandler.java:211) ~[Apugli-2.6.6+1.19.2-forge.jar%23468!/:2.6.6+1.19.2-forge] {re:classloading}
	at net.merchantpug.apugli.__ApugliForgeEventHandler_onLivingHurt_LivingHurtEvent.invoke(.dynamic) ~[Apugli-2.6.6+1.19.2-forge.jar%23468!/:2.6.6+1.19.2-forge] {re:classloading,pl:eventbus:B}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.3.jar%2351!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.3.jar%2351!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.3.jar%2351!/:?] {}
	at net.minecraftforge.common.ForgeHooks.onLivingHurt(ForgeHooks.java:343) ~[forge-1.19.2-43.3.0-universal.jar%23408!/:?] {re:mixin,re:classloading,pl:mixin:APP:apoli.mixins.json:forge.ForgeHooksMixin,pl:mixin:APP:tombstone.mixins.json:ForgeHooksMixin,pl:mixin:A}
	at net.minecraft.world.entity.LivingEntity.m_6475_(LivingEntity.java:1578) ~[server-1.19.2-20220805.130853-srg.jar%23403!/:?]'

I originally attributed the issue to Apugli, as I did not see what caused the server to crash the first time. Once I reproduced the issue by killing a zombie with the lightning breath, I closed that ticket and opened this one. The zombie at fault has the following information:

'-- Entity being ticked --
Details:
	Entity Type: minecraft:zombie (net.minecraft.world.entity.monster.Zombie)
	Entity ID: 614
	Entity Name: Zombie
	Entity's Exact location: 783.45, 77.00, 1657.89
	Entity's Block location: World: (783,77,1657), Section: (at 15,13,9 in 48,4,103; chunk contains blocks 768,-64,1648 to 783,319,1663), Region: (1,3; contains chunks 32,96 to 63,127, blocks 512,-64,1536 to 1023,319,2047)
	Entity's Momentum: 0.00, -0.08, -0.00
	Entity's Passengers: []
	Entity's Vehicle: null'

Here's the full log. I have to switch the server to peaceful and then swap it back to resolve the problem; otherwise, joining the server causes a crash.

[crash-2024-07-05_23.00.08-server.txt](https://github.com/user-attachments/files/16117033/crash-2024-07-05_23.00.08-server.txt)

**Comment by ChrysanthCow** [comment] 2024-08-17 20:22
Duplicate of #87. Will now be fixed on 1.19.2

**Closed as completed by ChrysanthCow** 2024-08-17 20:22 UTC
